name: azkar
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite:
  flutter_local_notifications:
  path_provider:
  percent_indicator:
  shared_preferences:
  intl:
  datetime_picker_formfield:
  provider:


flutter:

  uses-material-design: true

  assets:
    - Images/24998-black-white-800x500.png

  fonts:
    - family: ArefRuqaa
      fonts:
        - asset: fonts/ArefRuqaa-Regular.ttf